In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split,RandomizedSearchCV,GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score,f1_score,precision_score,make_scorer
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix,classification_report

In [3]:
data = pd.read_csv("Data/Transformation.csv")
# data.drop(columns=["loan_status.1"],inplace=True)

In [7]:
x = data.drop(columns=["loan_status"])
Y = data.iloc[:,27]

In [10]:
x_train,x_test,y_train,y_test = train_test_split(x,Y,test_size=0.2,random_state=23)

In [8]:
type(y_test)

pandas.core.series.Series

<h4>Logistic Regression</h4>

In [20]:
LR_model = LogisticRegression()
LR = LR_model.fit(x_train,y_train)
LR

c:\desktop\Loan-Approval-Model\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [21]:
Test = LR.predict(x_test)
Test

array([0, 0, 0, ..., 0, 0, 0], shape=(8999,))

In [10]:
data.columns

Index(['person_gender_female', 'person_gender_male',
       'person_education_Associate', 'person_education_Bachelor',
       'person_education_Doctorate', 'person_education_High School',
       'person_education_Master', 'person_home_ownership_MORTGAGE',
       'person_home_ownership_OTHER', 'person_home_ownership_OWN',
       'person_home_ownership_RENT', 'loan_intent_DEBTCONSOLIDATION',
       'loan_intent_EDUCATION', 'loan_intent_HOMEIMPROVEMENT',
       'loan_intent_MEDICAL', 'loan_intent_PERSONAL', 'loan_intent_VENTURE',
       'previous_loan_defaults_on_file_No',
       'previous_loan_defaults_on_file_Yes', 'person_age', 'person_emp_exp',
       'loan_int_rate', 'loan_percent_income', 'cb_person_cred_hist_length',
       'loan_status', 'person_income', 'loan_amnt', 'credit_score',
       'loan_status.1'],
      dtype='str')

In [23]:
accuracy = accuracy_score(y_test,Test)
precision_ = precision_score(y_test,Test)
print(accuracy)
print(precision_)

0.8852094677186354
0.75037147102526

In [34]:
#TUNING 

params = {
    'C': [0.01, 0.1, 1, 10],
    "penalty":["l2","l1"],
    "class_weight":[None,"balanced"],
    "solver":["liblinear"],
    "max_iter":[100,200,300]
}
RSV = RandomizedSearchCV(LR_model,params,cv=5,scoring='accuracy')
RSV = RSV.fit(x_train,y_train)
RSV

c:\desktop\Loan-Approval-Model\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\desktop\Loan-Approval-Model\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\desktop\Loan-Approval-Model\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\desktop\Loan-Approval-Model\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\desktop\Loan-Approval-Model\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\desktop\Loan-Approval-Model\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\desktop\Loan-Approval-Model\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1160: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\desktop\Loan-Approval-Model\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\desktop\Loan-Approval-Model\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1160: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\desktop\Loan-Approval-Model\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\desktop\Loan-Approval-Model\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1160: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\desktop\Loan-Approval-Model\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\desktop\Loan-Approval-Model\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1160: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\desktop\Loan-Approval-Model\.venv\Lib\site-packages\sklearn\svm\_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\desktop\Loan-Approval-Model\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\desktop\Loan-Approval-Model\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1160: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\desktop\Loan-Approval-Model\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\desktop\Loan-Approval-Model\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\desktop\Loan-Approval-Model\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\desktop\Loan-Approval-Model\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\desktop\Loan-Approval-Model\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\desktop\Loan-Approval-Model\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\desktop\Loan-Approval-Model\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1160: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\desktop\Loan-Approval-Model\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\desktop\Loan-Approval-Model\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1160: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\desktop\Loan-Approval-Model\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\desktop\Loan-Approval-Model\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1160: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\desktop\Loan-Approval-Model\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\desktop\Loan-Approval-Model\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1160: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\desktop\Loan-Approval-Model\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\desktop\Loan-Approval-Model\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1160: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\desktop\Loan-Approval-Model\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\desktop\Loan-Approval-Model\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1160: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\desktop\Loan-Approval-Model\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\desktop\Loan-Approval-Model\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1160: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\desktop\Loan-Approval-Model\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\desktop\Loan-Approval-Model\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1160: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\desktop\Loan-Approval-Model\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\desktop\Loan-Approval-Model\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1160: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\desktop\Loan-Approval-Model\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\desktop\Loan-Approval-Model\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1160: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\desktop\Loan-Approval-Model\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\desktop\Loan-Approval-Model\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1160: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\desktop\Loan-Approval-Model\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\desktop\Loan-Approval-Model\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1160: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\desktop\Loan-Approval-Model\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\desktop\Loan-Approval-Model\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1160: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\desktop\Loan-Approval-Model\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\desktop\Loan-Approval-Model\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1160: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\desktop\Loan-Approval-Model\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\desktop\Loan-Approval-Model\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1160: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\desktop\Loan-Approval-Model\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\desktop\Loan-Approval-Model\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\desktop\Loan-Approval-Model\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\desktop\Loan-Approval-Model\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\desktop\Loan-Approval-Model\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\desktop\Loan-Approval-Model\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\desktop\Loan-Approval-Model\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1160: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [0.01, 0.1, 1, 10],
                                        'class_weight': [None, 'balanced'],
                                        'max_iter': [100, 200, 300],
                                        'penalty': ['l2', 'l1'],
                                        'solver': ['liblinear']},
                   scoring='accuracy')

In [35]:
RSV.best_params_

{'solver': 'liblinear',
 'penalty': 'l1',
 'max_iter': 100,
 'class_weight': None,
 'C': 1}

In [36]:
LR_tune = LogisticRegression(solver='liblinear',penalty='l1',max_iter=100,class_weight=None,C= 1)
LR_tune = LR_tune.fit(x_train,y_train)
LR_tune

c:\desktop\Loan-Approval-Model\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\desktop\Loan-Approval-Model\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1160: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

LogisticRegression(C=1, penalty='l1', solver='liblinear')

In [37]:
Test_tune = LR_tune.predict(x_test)
Test_tune

array([0, 0, 0, ..., 0, 0, 0], shape=(8999,))

In [38]:
accuracy = accuracy_score(y_test,Test_tune)
precision_ = precision_score(y_test,Test_tune)
f1 = f1_score(y_test,Test_tune)
print(f1)
print(accuracy)
print(precision_)

0.7586034912718205
0.8924324924991666
0.7736520854526958

<h4>SVC</h4>

In [39]:
SVC_model = SVC(kernel="poly")
svc = SVC_model.fit(x_train,y_train)
svc

SVC(kernel='poly')

In [40]:
predict = svc.predict(x_test)
predict

array([0, 0, 0, ..., 0, 0, 0], shape=(8999,))

In [42]:
print(accuracy_score(y_test,predict))
print(precision_score(y_test,predict))
print(f1_score(y_test,predict))

0.8785420602289143
0.7769365171811299
0.7093858016484977

In [43]:
f1_ = make_scorer(f1_score)
params = {
    'C': np.logspace(-2, 2, 10),
    "kernel":["rbf","poly","linear"],
    "gamma":[0.1,1,10,"scale","auto"],
    "degree":[2,3,5]
}
svc_tune = RandomizedSearchCV(SVC_model,params,cv=5,n_iter=10,scoring=f1_)
svc_tune.fit(x_train,y_train)
svc_tune

KeyboardInterrupt:

In [17]:
best_model = svc_tune.best_estimator_
pred = best_model.predict(x_test)
print(svc_tune.best_score_)
print("f1 score:",f1_score(y_test,pred,pos_label="Y"))
print("accuracy:",accuracy_score(y_test,pred))
print("precision:",precision_score(y_test,pred,pos_label="Y"))

0.8523652040382756
f1 score: 0.7975460122699386
accuracy: 0.7317073170731707
precision: 0.7471264367816092

<H4>KNN</H4>

In [44]:
KNN = KNeighborsClassifier(n_neighbors=10)
KNN = KNN.fit(x_train,y_train)
KNN

KNeighborsClassifier(n_neighbors=10)

In [45]:
predict = KNN.predict(x_test)
predict

array([0, 0, 0, ..., 0, 0, 0], shape=(8999,))

In [46]:
print(f1_score(y_test,predict))
print(accuracy_score(y_test,predict))
print(precision_score(y_test,predict))

0.6172474896633195
0.8559839982220246
0.7786885245901639

In [21]:
# Tune
params = {
    "n_neighbors":[5,10,12,15],
    "weights":["uniform","distance"],
    "algorithm":["kd_tree","ball_tree","brute","auto"],
    "leaf_size":[10,15,30,50,100]
}
f1_ = make_scorer(f1_score,pos_label="Y")
knn_tune = RandomizedSearchCV(KNN,param_distributions=params,scoring=f1_,n_iter=10,cv=5)
knn_tune.fit(x_train,y_train)
knn_tune

RandomizedSearchCV(cv=5, estimator=KNeighborsClassifier(n_neighbors=10),
                   param_distributions={'algorithm': ['kd_tree', 'ball_tree',
                                                      'brute', 'auto'],
                                        'leaf_size': [10, 15, 30, 50, 100],
                                        'n_neighbors': [5, 10, 12, 15],
                                        'weights': ['uniform', 'distance']},
                   scoring=make_scorer(f1_score, response_method='predict', pos_label=Y))

In [27]:
best_model = knn_tune.best_estimator_
predict = best_model.predict(x_test)
print(knn_tune.best_score_)
print("f1_score:",f1_score(y_test,predict,pos_label="Y"))
print(accuracy_score(y_test,predict))
print(precision_score(y_test,predict,pos_label="Y"))

0.8270334069034595
f1_score: 0.7807486631016043
0.6666666666666666
0.6576576576576577

## Decision Tree

In [11]:
New_data = pd.read_csv("Data/transformation_org.csv")
New_data.head()

,person_gender_female,person_gender_male,person_education_Associate,person_education_Bachelor,person_education_Doctorate,person_education_High School,person_education_Master,person_home_ownership_MORTGAGE,person_home_ownership_OTHER,person_home_ownership_OWN,...,previous_loan_defaults_on_file_Yes,person_age,person_income,person_emp_exp,loan_amnt,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,loan_status
0,1,0,0,0,0,0,1,0,0,0,...,0,22.0,71948.0,0,3217900.0,16.02,0.49,3.0,561,1
1,1,0,0,0,0,1,0,0,0,1,...,1,21.0,12282.0,0,91940.0,11.14,0.08,2.0,504,0
2,1,0,0,0,0,1,0,1,0,0,...,0,25.0,12438.0,3,505670.0,12.87,0.44,3.0,635,1
3,1,0,0,1,0,0,0,0,0,0,...,0,23.0,79753.0,0,3217900.0,15.23,0.44,2.0,675,1
4,0,1,0,0,0,0,1,0,0,0,...,0,24.0,66135.0,1,3217900.0,14.27,0.53,4.0,586,1

In [12]:
X = New_data.drop(columns=["loan_status"])
y = New_data.iloc[:,27]
X_train,X_test,Y_train,Y_test = train_test_split(X,y,test_size=0.20,random_state=33)

In [13]:
dtc = DecisionTreeClassifier(criterion='entropy',min_samples_split=2,min_samples_leaf=8,max_depth=5)
dtc.fit(X_train,Y_train)
dtc

DecisionTreeClassifier(criterion='entropy', max_depth=5, min_samples_leaf=8)

In [14]:
predict = dtc.predict(X_test)
print("f1_score:",f1_score(Y_test,predict))
print(accuracy_score(Y_test,predict))
print(precision_score(Y_test,predict))

f1_score: 0.7857142857142857
0.9099899988887654
0.84375

In [15]:
#tuning
params = {
    "criterion":["gini","entropy","log_loss"],
    "splitter":["best","random"],
    "min_samples_split":[2,4,8,10,15],
    "min_samples_leaf":[2,5,8,10],
    "max_depth":[2,5,8,10]
}
f1_ = make_scorer(f1_score)
dtc_tune = RandomizedSearchCV(dtc,param_distributions=params,scoring=f1_,cv=5,n_iter=10)
dtc_tune.fit(X_train,Y_train)
dtc_tune

RandomizedSearchCV(cv=5,
                   estimator=DecisionTreeClassifier(criterion='entropy',
                                                    max_depth=5,
                                                    min_samples_leaf=8),
                   param_distributions={'criterion': ['gini', 'entropy',
                                                      'log_loss'],
                                        'max_depth': [2, 5, 8, 10],
                                        'min_samples_leaf': [2, 5, 8, 10],
                                        'min_samples_split': [2, 4, 8, 10, 15],
                                        'splitter': ['best', 'random']},
                   scoring=make_scorer(f1_score, response_method='predict'))

In [16]:
best_model = dtc_tune.best_estimator_
predict = best_model.predict(X_test)
print("f1_score:",f1_score(Y_test,predict))
print(accuracy_score(Y_test,predict))
print(precision_score(Y_test,predict))

f1_score: 0.8109706910459801
0.9218802089121013
0.8875809299587993

In [17]:
dtc_tune.best_params_

{'splitter': 'best',
 'min_samples_split': 2,
 'min_samples_leaf': 10,
 'max_depth': 10,
 'criterion': 'gini'}

## Ensemble Technique: Stacking Classifier

In [ ]:
# #splitting x_train and y_train 50/50
# x_train_a,x_train_b,y_train_a,y_train_b = train_test_split(x_train,y_train,test_size=.50,random_state=23)
# #base models
# lg = LogisticRegression()
# svc = SVC()
# knn = KNeighborsClassifier()
# #training base models
# lg.fit(x_train_a,y_train_a)
# svc.fit(x_train_a,y_train_a)
# knn.fit(x_train_a,y_train_a)
# #prediction on base models
# pred_lg = lg.predict(x_train_b)
# pred_svc = svc.predict(x_train_b)
# pred_knn = knn.predict(x_train_b)
# #stacking up those prediction 
# input_features = np.column_stack((pred_lg,pred_svc,pred_knn))
# #encoding input_features
# encoders = []
# input_encode = np.empty_like(input_features,dtype="int")
# for i in range(input_features.shape[1]):
#     lblencoder = LabelEncoder()
#     input_encode[:,i] = lblencoder.fit_transform(input_features[:,i])
#     encoders.append(lblencoder)
# #train meta model dt using these input_features
# dt = DecisionTreeClassifier()
# dt.fit(input_encode,y_train_b)

# # prediction on test
# pred_lg_test = lg.predict(x_test)
# pred_svc_test = lg.predict(x_test)
# pred_knn_test = lg.predict(x_test)
# #stack it up
# input_features_test = np.column_stack((pred_lg_test,pred_svc_test,pred_knn_test))
# #encoding 
# encoders_test = []
# input_encoder_test = np.empty_like(input_features_test,dtype="int")
# for i in range(input_encoder_test.shape[1]):
#     le = LabelEncoder()
#     input_encoder_test[:,i] = le.fit_transform(input_features_test[:,i])
#     encoders_test.append(le)
# #final prediction
# final_prediction = dt.predict(input_encoder_test)
# final_prediction

array(['Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y',
       'Y', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N',
       'Y', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'N', 'N', 'Y', 'N', 'Y', 'N',
       'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'N', 'N', 'Y', 'Y',
       'N', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'N', 'Y', 'Y', 'N', 'Y', 'Y',
       'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y',
       'N', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y',
       'N', 'Y', 'Y', 'N', 'Y', 'Y', 'N', 'N', 'N', 'N', 'Y', 'N', 'Y',
       'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'N', 'Y', 'Y', 'Y',
       'N', 'N', 'Y', 'Y', 'Y', 'N'], dtype=object)

In [ ]:
# print(f1_score(y_test,final_prediction,pos_label="Y"))
# print(accuracy_score(y_test,final_prediction))
# print(precision_score(y_test,final_prediction,pos_label="Y"))

0.7901234567901234
0.7235772357723578
0.7441860465116279

In [ ]:
# import joblib
# model = joblib.dump(dtc_tune,"Models/DecisionTree.pkl")
# joblib.dump(lg,"Models/stackingBaseLG.pkl")
# joblib.dump(svc,"Models/stackingBaseSVC.pkl")
# joblib.dump(knn,"Models/stackingBaseKNN.pkl")
# joblib.dump(dt,"Models/stackingMetaDT.pkl")

## Classification Report

In [18]:
print(classification_report(Y_test,predict)) # DecisionTreeClassifier

              precision    recall  f1-score   support

           0       0.93      0.97      0.95      6979
           1       0.89      0.75      0.81      2020

    accuracy                           0.92      8999
   macro avg       0.91      0.86      0.88      8999
weighted avg       0.92      0.92      0.92      8999

In [18]:
y_test.to_frame()

       loan_status
22667            1
23807            0
11545            0
23063            0
44153            1
...            ...
9419             0
26090            0
38840            0
13126            0
38678            0

[8999 rows x 1 columns]

In [25]:
d = pd.read_csv("ytrain.csv")
f = pd.read_csv("ytest.csv")
xtr = pd.read_csv("xtrain.csv")
xtst = pd.read_csv("xtest.csv")

In [ ]:
xtr.isnull().sum()

person_gender_female                  5
person_gender_male                    5
person_education_Associate            5
person_education_Bachelor             5
person_education_Doctorate            5
person_education_High School          5
person_education_Master               5
person_home_ownership_MORTGAGE        5
person_home_ownership_OTHER           5
person_home_ownership_OWN             5
person_home_ownership_RENT            5
loan_intent_DEBTCONSOLIDATION         5
loan_intent_EDUCATION                 5
loan_intent_HOMEIMPROVEMENT           5
loan_intent_MEDICAL                   5
loan_intent_PERSONAL                  5
loan_intent_VENTURE                   5
previous_loan_defaults_on_file_No     5
previous_loan_defaults_on_file_Yes    5
person_age                            5
person_income                         5
person_emp_exp                        5
loan_amnt                             5
loan_int_rate                         5
loan_percent_income                   5
cb_person_cred_hist_length            5
credit_score                          5
dtype: int64